// Generated by Skyramp v1.3.19 on 2026-04-19 04:42:32.880596119 +0000 UTC m=+134.020651066
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add_to_bag_quantity_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/add_to_bag_quantity_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByLabel("Qty:").selectOption("3");
    await page.getByRole("button", { name: "Add to Bag" }).click();
    await expect(page.getByTestId("cart-heading")).toContainText("Cart (3)");
    await expect(page.getByText("Quantity:")).toContainText(" 3");
    await expect(page.getByText("$59.97")).toBeVisible();

    expect(errors).toHaveLength(0);
});
