// Generated by Skyramp v1.3.19 on 2026-04-19 04:23:24.127047903 +0000 UTC m=+269.906740588
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output billing_address_toggle.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/billing_address_toggle_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/66VCHSJNUP");
    await page.getByRole("button", { name: "Add To Cart" }).click();

    await expect(page.getByRole('heading', { name: 'Billing Address' })).toBeVisible();
    await expect(page.getByLabel('Billing Street Address')).toBeHidden();

    await page.getByRole("checkbox", { name: "Same as shipping address" }).click();

    await expect(page.getByLabel('Billing Street Address')).toBeVisible();
    await expect(page.getByLabel('Billing City')).toBeVisible();
    expect(errors).toHaveLength(0);
});
