// Generated by Skyramp v1.3.19 on 2026-04-19 03:21:18.671346071 +0000 UTC m=+273.781997452
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output carousel_prev_nav.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/carousel_prev_nav_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(100000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.waitForLoadState('networkidle');
    await expect(page.getByRole("link", { name: "Sunglasses Sunglasses $" })).toContainText("Sunglasses");

    await page.getByRole("button", { name: "Next" }).click();
    await expect(page.getByRole("button", { name: "Previous" })).toBeVisible();

    await page.getByRole("button", { name: "Previous" }).click();
    await expect(page.getByRole("link", { name: "Sunglasses Sunglasses $" })).toContainText("Sunglasses");

    expect(errors).toHaveLength(0);
});
