// Generated by Skyramp v1.3.19 on 2026-04-19 03:23:15.78657456 +0000 UTC m=+390.897225941
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output carousel_to_cart.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/carousel_to_cart_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(152000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.waitForLoadState('networkidle');
    await page.getByRole("link", { name: "Tank Top Tank Top $" }).waitFor({ state: 'visible', timeout: 10000 });

    await page.getByRole("link", { name: "Tank Top Tank Top $" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByRole("heading", { name: "Tank Top" })).toContainText("Tank Top");

    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByRole("heading", { name: "Cart (1)" })).toContainText("Cart (1)");
    await expect(page.getByRole("heading", { name: "Tank Top", level: 4 })).toContainText("Tank Top");

    expect(errors).toHaveLength(0);
});
