// Generated by Skyramp v1.3.19 on 2026-04-19 04:22:48.577820084 +0000 UTC m=+196.235652498
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_with_items_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_with_items_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("cart-heading")).toContainText("Cart (1)");
    await expect(page.getByTestId("place-order-btn")).toContainText("Place Order");
    expect(errors).toHaveLength(0);
});
