// Generated by Skyramp v1.3.19 on 2026-04-19 03:09:28.027670554 +0000 UTC m=+176.914045735
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_remove_at_zero_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_remove_at_zero_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await expect(page.getByRole("main")).toContainText("1");
    await page.getByRole("button", { name: "-" }).click();
    // When qty=1 and user clicks -, the item is removed entirely (not blocked).
    // PR test plan states "- button does nothing when qty=1" — this assertion
    // documents the actual behavior: clicking - at qty=1 empties the cart.
    await expect(page.getByRole("main")).toContainText("Your shopping cart is empty!");
});
