// Generated by Skyramp v1.3.19 on 2026-04-19 03:09:26.33863241 +0000 UTC m=+175.225007591
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_quantity_decrease_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_quantity_decrease_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.locator('#quantity').selectOption("3");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await expect(page.getByRole("main")).toContainText("3");
    await page.getByRole("button", { name: "-" }).click();
    await expect(page.getByRole("main")).toContainText("2");
    await expect(page.getByRole("main")).toContainText("$39.98");
    await expect(page.getByRole("main")).toContainText("Cart (2)");
});
