// Generated by Skyramp v1.3.19 on 2026-04-19 01:02:41.73769945 +0000 UTC m=+305.729962508
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_total_preserved_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_total_preserved_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(113000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("button", { name: "Empty Cart" }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByText("$28.98")).toBeVisible();
    await expect(page.getByText("$19.99")).toBeVisible();
    expect(errors).toHaveLength(0);
});
