// Generated by Skyramp v1.3.19 on 2026-04-19 04:40:15.422930703 +0000 UTC m=+96.398486597
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_empty_state_new_messages_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_empty_state_new_messages_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/cart");
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("empty-cart")).toBeVisible();
    await expect(page.getByRole('heading', { name: 'No items in your cart yet.' })).toBeVisible();
    await expect(page.getByText("Browse our products and add")).toContainText("Browse our products and add something you love!");
    expect(errors).toHaveLength(0);
});
