// Generated by Skyramp v1.3.19 on 2026-04-19 04:40:11.996015825 +0000 UTC m=+92.971571708
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_clear_all_items_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_clear_all_items_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/66VCHSJNUP");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("cart-heading")).toContainText("Shopping Bag (1)");
    await page.getByTestId("empty-cart-btn").click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/cart");
    await expect(page.getByTestId("empty-cart")).toBeVisible();
    expect(errors).toHaveLength(0);
});
