// Generated by Skyramp v1.3.19 on 2026-04-19 03:19:13.797317396 +0000 UTC m=+217.674422753
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_breadcrumb_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_breadcrumb_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await expect(page.getByRole('navigation', { name: 'breadcrumb' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Home' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Cart (1)' })).toBeVisible();
    expect(errors).toHaveLength(0);
});
