// Generated by Skyramp v1.3.19 on 2026-04-19 03:23:16.525930097 +0000 UTC m=+181.876683171
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output checkout_happy_path.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/checkout_happy_path_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/L9ECAV7KIM");
    await page.getByRole("button", { name: "Add To Cart" }).click();

    // Assert Step 1 progress indicator is visible with Shipping label
    await expect(page.getByText("Shipping", { exact: true }).first()).toBeVisible();

    await page.getByRole("button", { name: "Next: Payment →" }).click();

    // Assert Step 2 Payment form is shown
    await expect(page.getByRole("heading", { name: "Payment Method" })).toBeVisible();

    await page.getByRole("button", { name: "Next: Review →" }).click();

    // Assert Step 3 review is shown with order summary
    await expect(page.getByRole("heading", { name: "Review Your Order" })).toBeVisible();
    await expect(page.getByText("Card: **** **** ****")).toContainText("**** **** **** 0454");
    await expect(page.getByRole("button", { name: "Place Order" })).toBeVisible();

    expect(errors).toHaveLength(0);
});
