// Generated by Skyramp v1.3.19 on 2026-04-19 04:23:25.427400842 +0000 UTC m=+271.207093537
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output checkout_dropdowns.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/checkout_dropdowns_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/2ZYFJ3GM2N");
    await page.getByRole("button", { name: "Add To Cart" }).click();

    await expect(page.getByLabel('State')).toBeVisible();
    await expect(page.getByLabel('Country')).toBeVisible();

    await page.getByLabel("State").selectOption("NY");
    await page.getByRole("button", { name: "Place Order" }).click();

    await expect(page.getByRole('heading', { name: 'Your order is complete!' })).toBeVisible();
    await expect(page.getByText('Mountain View, NY')).toBeVisible();
    expect(errors).toHaveLength(0);
});
