// Generated by Skyramp v1.3.19 on 2026-04-19 03:24:54.645858093 +0000 UTC m=+279.996611176
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output checkout_back_navigation.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/checkout_back_navigation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/6E92ZMYYFZ");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("button", { name: "Next: Payment →" }).click();

    // Assert Step 2 Payment is active before going back
    await expect(page.getByRole("heading", { name: "Payment Method" })).toBeVisible();

    await page.getByRole("button", { name: "← Back: Shipping" }).click();

    // Assert Step 1 Shipping is restored and form values are preserved
    await expect(page.getByRole("heading", { name: "Shipping Address" })).toBeVisible();
    await expect(page.getByRole("textbox", { name: "E-mail Address" })).toHaveValue("someone@example.com");
    await expect(page.getByRole("heading", { name: "Payment Method" })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
