// Generated by Skyramp v1.3.19 on 2026-04-19 03:24:08.408019632 +0000 UTC m=+233.758772725
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output checkout_validation.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/checkout_validation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/L9ECAV7KIM");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("textbox", { name: "E-mail Address" }).fill(" ");
    await page.getByRole("button", { name: "Next: Payment →" }).click();

    // Assert validation error is shown and Step 1 remains active (form does not advance)
    await expect(page.getByText("Please enter a valid email")).toContainText("Please enter a valid email address");
    await expect(page.getByRole("heading", { name: "Shipping Address" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Payment Method" })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
