// Generated by Skyramp v1.3.19 on 2026-04-19 01:02:38.366296505 +0000 UTC m=+302.358559573
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output confirm_empty_cart_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/confirm_empty_cart_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("button", { name: "Empty Cart" }).click();
    await expect(page.getByText("Are you sure you want to")).toContainText("Are you sure you want to empty your cart?");
    await page.getByRole("button", { name: "Confirm" }).click();
    await expect(page.getByRole("heading", { name: "Hot Products" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Cart icon", exact: true })).toBeVisible();
    expect(errors).toHaveLength(0);
});
