// Generated by Skyramp v1.3.19 on 2026-04-19 03:25:44.614649045 +0000 UTC m=+446.738056479
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output email_preview_multiitem_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/email_preview_multiitem_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(96000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/1YMWWN1N4O");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.goto("http://localhost:8080/product/6E92ZMYYFZ");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("textbox", { name: "E-mail Address" }).fill("multiitem@test.example");
    await page.getByRole("button", { name: "Place Order" }).click();
    await expect(page.getByRole("heading", { name: "Your order is complete!" })).toBeVisible();
    await page.getByRole("button", { name: "View Order Confirmation Email" }).click();
    await expect(page.getByRole("row", { name: "1YMWWN1N4O 1 $" })).toContainText("1YMWWN1N4O");
    await expect(page.getByRole("row", { name: "6E92ZMYYFZ 1 $" })).toContainText("6E92ZMYYFZ");
    await expect(page.getByRole("strong").filter({ hasText: "$127.97" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
