// Generated by Skyramp v1.3.19 on 2026-04-19 03:25:34.20777141 +0000 UTC m=+436.331178844
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output email_preview_toggle_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/email_preview_toggle_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(231000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("textbox", { name: "E-mail Address" }).fill("testuser@skyramp.dev");
    await page.getByRole("button", { name: "Place Order" }).click();
    await expect(page.getByRole("heading", { name: "Your order is complete!" })).toBeVisible();
    await expect(page.getByRole("button", { name: "View Order Confirmation Email" })).toBeVisible();
    await page.getByRole("button", { name: "View Order Confirmation Email" }).click();
    await expect(page.getByRole("button", { name: "Hide Order Confirmation Email" })).toBeVisible();
    await expect(page.getByRole("row", { name: "OLJCESPC7Z 1 $" })).toContainText("OLJCESPC7Z");
    await page.getByRole("button", { name: "Hide Order Confirmation Email" }).click();
    await expect(page.getByRole("button", { name: "View Order Confirmation Email" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
