// Generated by Skyramp v1.3.19 on 2026-04-19 03:25:41.214768919 +0000 UTC m=+443.338176382
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output email_preview_content_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/email_preview_content_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(79000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/66VCHSJNUP");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("textbox", { name: "E-mail Address" }).fill("buyer@testshop.example");
    await page.getByRole("textbox", { name: "Street Address" }).fill("500 Main St");
    await page.getByRole("textbox", { name: "City" }).fill("San Francisco");
    await page.getByRole("textbox", { name: "State" }).fill("CA");
    await page.getByRole("textbox", { name: "Zip Code" }).fill("94105");
    await page.getByRole("button", { name: "Place Order" }).click();
    await expect(page.getByRole("heading", { name: "Your order is complete!" })).toBeVisible();
    await page.getByRole("button", { name: "View Order Confirmation Email" }).click();
    await expect(page.getByRole("heading", { name: "Order Items" })).toBeVisible();
    await expect(page.getByRole("row", { name: "66VCHSJNUP 1 $" })).toContainText("66VCHSJNUP");
    await expect(page.getByRole("row", { name: "66VCHSJNUP 1 $" })).toContainText("$18.99");
    await expect(page.getByRole("heading", { name: "Shipping Address" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
