// Generated by Skyramp v1.3.19 on 2026-04-19 04:23:18.29673319 +0000 UTC m=+264.076425875
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output gift_message_checkout.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/gift_message_checkout_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("textbox", { name: "Gift Message (optional)" }).fill("Happy Birthday! Hope you enjoy this gift.");
    await page.getByRole("button", { name: "Place Order" }).click();

    await expect(page.getByRole('heading', { name: 'Your order is complete!' })).toBeVisible();
    // BUG: Gift message should appear on confirmation but doesn't — form sends name="giftMsg" but handler reads r.FormValue("gift_message")
    await expect(page.getByText("Happy Birthday! Hope you enjoy this gift.")).toBeVisible();
    expect(errors).toHaveLength(0);
});
