// Generated by Skyramp v1.3.19 on 2026-04-19 03:20:12.587765216 +0000 UTC m=+276.464870582
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_breadcrumb_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/order_breadcrumb_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("button", { name: "Place Order" }).click();
    await expect(page.getByRole('navigation', { name: 'breadcrumb' })).toBeVisible();
    await expect(page.getByRole('navigation', { name: 'breadcrumb' })).toContainText("Order Confirmation");
    await expect(page.getByRole('heading', { name: 'Your order is complete!' })).toBeVisible();
    await page.getByRole("button", { name: "Continue Shopping" }).click();
    await expect(page.getByRole('heading', { name: 'Hot Products' })).toBeVisible();
    expect(errors).toHaveLength(0);
});
