// Generated by Skyramp v1.3.19 on 2026-04-19 04:23:21.078099077 +0000 UTC m=+397.176055699
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_page_negative_quantity.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/ui_negative_quantity_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 30000;

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/product/66VCHSJNUP");
    await page.getByRole("spinbutton", { name: "Quantity:" }).fill("-1");

    // Click Add To Cart with -1 quantity — server should reject (422) but removed validation accepts it (bug)
    // /cart may hang when rendering a cart with a negative quantity item
    try {
        await page.getByRole("button", { name: "Add To Cart" }).click();
    } catch (e) { /* navigation to /cart may hang due to -1 quantity bug */ }

    // Navigate home with a lenient wait to check cart badge state
    try {
        await page.goto("http://localhost:8080", { waitUntil: "domcontentloaded", timeout: 30000 });
    } catch (e) { /* recover from detached frame */ }

    // Assert cart badge is NOT negative — documents missing validation: server accepts -1 quantity
    await expect(page.getByText("-1")).not.toBeVisible();
});
