// Generated by Skyramp v1.3.19 on 2026-04-18 23:05:56.741113911 +0000 UTC m=+378.823301685
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_zoom_cart_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_zoom_add_to_cart_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.waitForLoadState('networkidle');

    await page.goto("http://localhost:8080/product/6E92ZMYYFZ");
    await page.waitForLoadState('networkidle');

    await expect(page.getByRole('heading', { name: 'Mug' })).toBeVisible();

    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.waitForLoadState('networkidle');

    await expect(page.getByRole('heading', { name: 'Cart (1)' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Mug' })).toBeVisible();

    expect(errors).toHaveLength(0);
});
