// Generated by Skyramp v1.3.19 on 2026-04-19 04:26:01.437203858 +0000 UTC m=+557.535160470
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_page_default_quantity.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/ui_default_quantity_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/1YMWWN1N4O");
    await expect(page.getByText("Quantity:")).toBeVisible();
    await expect(page.getByRole("spinbutton", { name: "Quantity:" })).toHaveValue("1");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await expect(page.getByRole("heading", { name: "Cart (1)" })).toBeVisible();
    await expect(page.getByText("$109.99")).toBeVisible();
    expect(errors).toHaveLength(0);
});
