// Generated by Skyramp v1.3.19 on 2026-04-19 04:22:59.801695458 +0000 UTC m=+164.386139323
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_page_render_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_page_render_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");

    await expect(page.getByRole('heading', { name: 'Sunglasses' })).toBeVisible();
    await expect(page.getByText("Add a modern touch to your")).toContainText("Add a modern touch to your outfits with these sleek aviator sunglasses.");
    // PR adds <h3>You May Also Like</h3> but the recommendations template already has <h2>You May Also Like</h2>
    // This assertion will FAIL while the duplicate heading bug exists — expected 1 heading, got 2
    await expect(page.getByRole('heading', { name: 'Recommended for You' })).toHaveCount(1);

    expect(errors).toHaveLength(0);
});
