// Generated by Skyramp v1.3.19 on 2026-04-19 04:23:01.657556887 +0000 UTC m=+166.242000752
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_add_to_cart_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_add_to_cart_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("button", { name: "Add to Bag" }).click();

    await expect(page.getByRole('heading', { name: 'Cart (1)' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Sunglasses' })).toBeVisible();
    await expect(page.getByText('$28.98')).toBeVisible();

    expect(errors).toHaveLength(0);
});
