// Generated by Skyramp v1.3.19 on 2026-04-18 23:04:20.523198353 +0000 UTC m=+282.605386086
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_zoom_hover_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_zoom_hover_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(206000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.waitForLoadState('networkidle');

    await expect(page.getByRole('heading', { name: 'Sunglasses' })).toBeVisible();
    await expect(page.getByText('$19.99')).toBeVisible();

    await page.getByRole("main").hover();

    expect(errors).toHaveLength(0);
});
