// Generated by Skyramp v1.3.19 on 2026-04-19 04:19:36.876730808 +0000 UTC m=+172.974687430
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_page_custom_quantity.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/ui_custom_quantity_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await expect(page.getByRole("spinbutton", { name: "Quantity:" })).toHaveValue("1");
    await page.getByRole("spinbutton", { name: "Quantity:" }).fill("3");
    await expect(page.getByRole("spinbutton", { name: "Quantity:" })).toHaveValue("3");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await expect(page.getByRole("heading", { name: "Cart (3)" })).toBeVisible();
    await expect(page.getByText("Quantity: 3")).toBeVisible();
    await expect(page.getByText("$59.97")).toBeVisible();
    expect(errors).toHaveLength(0);
});
