// Generated by Skyramp v1.3.19 on 2026-04-18 23:06:50.355245266 +0000 UTC m=+432.437432999
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_zoom_currency_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_zoom_currency_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/1YMWWN1N4O");
    await page.waitForLoadState('networkidle');

    await expect(page.getByRole('heading', { name: 'Watch' })).toBeVisible();
    await expect(page.getByText('$109.99')).toBeVisible();

    await page.locator('select[name="currency_code"]').selectOption('EUR');
    await page.waitForLoadState('networkidle');

    await expect(page.getByText('€97.29')).toBeVisible();

    expect(errors).toHaveLength(0);
});
