// Generated by Skyramp v1.3.19 on 2026-04-19 04:42:34.212492633 +0000 UTC m=+135.352547589
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recommendations_heading_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/recommendations_heading_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await expect(page.getByRole('heading', { name: 'Recommended for You' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Add to Bag' })).toBeVisible();

    await page.goto("http://localhost:8080/product/0PUK6V6EV0");
    await expect(page.getByRole('heading', { name: 'Recommended for You' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Add to Bag' })).toBeVisible();

    expect(errors).toHaveLength(0);
});
