// Generated by Skyramp v1.3.19 on 2026-04-19 03:10:59.013486904 +0000 UTC m=+203.181112448
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output search_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/search_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    const errors: string[] = [];
    page.on('pageerror', (err: Error) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    await page.getByRole("textbox", { name: "Search products..." }).fill("Sunglasses");
    await page.getByRole("button", { name: "Search" }).click();
    await expect(page.getByRole("heading", { name: "Search results for " })).toContainText("Search results for");
    await expect(page.getByRole("textbox", { name: "Search products..." })).toHaveValue("Sunglasses");
    await page.goto("http://localhost:8080/search?q=zzyzx123nonexistent");
    await expect(page.getByRole("heading", { name: "Search results for " })).toContainText("Search results for");
    await expect(page.getByRole("textbox", { name: "Search products..." })).toHaveValue("zzyzx123nonexistent");
    await expect(page.getByText("No products found")).toBeVisible();
    await page.goto("http://localhost:8080/search?q=Sunglasses");
    await page.getByRole("main").getByRole("link").click();
    await expect(page.getByRole("heading", { name: "Sunglasses" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
