// Generated by Skyramp v1.3.19 on 2026-04-19 03:13:03.052124469 +0000 UTC m=+327.219750013
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output search_from_product_page_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/search_from_product_page_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: string[] = [];
    page.on('pageerror', (err: Error) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await page.getByRole("textbox", { name: "Search products..." }).fill("Watch");
    await page.getByRole("button", { name: "Search" }).click();
    await expect(page.getByRole("heading", { name: "Search results for " })).toContainText("Search results for");
    await expect(page.getByRole("textbox", { name: "Search products..." })).toHaveValue("Watch");
    expect(errors).toHaveLength(0);
});
