// Generated by Skyramp v1.3.19 on 2026-04-18 22:15:48.190071766 +0000 UTC m=+135.971660254
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/footer_testbot_label_homepage_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080");
    await expect(page.getByRole("paragraph").filter({ hasText: "TestBot Evaluation Instance" })).toBeVisible();
    await expect(page.getByRole("main")).toContainText("This website is hosted for demo purposes only");
    expect(errors).toHaveLength(0);
});
